<?php

namespace AppBundle\Repository;

/**
 * AdjustmentLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdjustmentLineRepository extends \Doctrine\ORM\EntityRepository
{
}
