<?php

namespace AppBundle\Repository;

/**
 * AdjustmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdjustmentRepository extends \Doctrine\ORM\EntityRepository
{
}
